# You can write down any information and it will be available
# at the address /api/info (if you use default nginx config).
# If server.host (str) will be defained then this value
# will be displayed in the web interface.

server:
    host: localhost.localdomain

kvm: {}
