FROM scratch

ADD "pikvm-os-v2-hdmiusb-pi-builder-arm-base-rootfs-generic.tgz" /
COPY "qemu-arm-static" "/usr/bin/qemu-arm-static"

RUN mkdir -p /etc/pacman.d/hooks \
	&& ln -s /dev/null /etc/pacman.d/hooks/30-systemd-tmpfiles.hook
ARG BOARD
ENV BOARD $BOARD

ARG ARCH
ENV ARCH $ARCH

ARG LOCALE
ENV LOCALE $LOCALE

ARG TIMEZONE
ENV TIMEZONE $TIMEZONE

ARG REPO_URL
ENV REPO_URL $REPO_URL

ARG PIKVM_REPO_URL
ENV PIKVM_REPO_URL $PIKVM_REPO_URL

ARG PIKVM_REPO_KEY
ENV PIKVM_REPO_KEY $PIKVM_REPO_KEY
